M48
; DRILL file {KiCad (6.0.4)} date Tue Apr 19 23:10:40 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-19T23:10:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X103.2Y-73.2
X103.2Y-89.7
X126.4Y-73.1
X126.4Y-89.7
T0
M30
