M48
; DRILL file {KiCad 9.0.5} date 2025-10-18T12:32:47+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-18T12:32:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X144.99Y-89.92
X145.0Y-136.61
X156.01Y-136.62
X156.02Y-89.92
M30
