M48
; DRILL file {KiCad 9.0.5} date 2025-10-20T18:48:50+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-20T18:48:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X134.142Y-86.27
T2
X80.0Y-82.0
X80.0Y-126.0
X133.491Y-98.286
X150.0Y-126.0
X153.0Y-103.0
X230.0Y-82.0
X230.0Y-126.0
M30
