M48
; DRILL file {KiCad 9.0.5} date 2025-10-20T01:09:00+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-20T01:09:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,Plated,1,4,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.600
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.800
%
G90
G05
T1
X107.5Y-66.34
X107.5Y-75.1
T2
X100.89Y-66.36
X100.91Y-75.07
X108.9Y-73.8
X115.2Y-74.0
T3
X118.41Y-69.75
X121.91Y-72.25
X128.1Y-73.2
X133.1Y-68.2
M30
