M48
; DRILL file {KiCad (6.0.4)} date Wed Apr 20 18:40:47 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-20T18:40:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X106.7Y-121.0
X130.0Y-82.6
X153.3Y-121.0
T0
M30
