M48
; DRILL file {KiCad 9.0.5} date 2025-10-18T11:17:39+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-18T11:17:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.150
%
G90
G05
T1
X118.3Y-69.9
X122.85Y-67.0
T2
X113.86Y-74.44
X116.4Y-74.44
X118.94Y-74.44
T3
X122.7Y-74.4
M30
