M48
; DRILL file {KiCad 9.0.5} date 2025-10-20T17:56:03+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-20T17:56:03+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X87.0Y-55.0
X87.0Y-123.0
X187.0Y-123.0
X214.0Y-70.95
X214.0Y-92.55
X225.0Y-55.0
X225.0Y-123.0
M30
